/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRegistration;

/**
 *
 * @author rtspi
 */
public class UserRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserRegistrationJPanel
     */
    public UserRegistrationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        counsellingJLabel = new javax.swing.JLabel();
        zipcodeJLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        phoneJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        sexJLabel = new javax.swing.JLabel();
        aidJLabel = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        stateJTextField = new javax.swing.JTextField();
        zipcodeJTextField = new javax.swing.JTextField();
        phoneJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        addressJTextField = new javax.swing.JTextField();
        chkFemale = new javax.swing.JCheckBox();
        chkOthers = new javax.swing.JCheckBox();
        chkYes1 = new javax.swing.JCheckBox();
        chkNo1 = new javax.swing.JCheckBox();
        chkYes2 = new javax.swing.JCheckBox();
        chkNo2 = new javax.swing.JCheckBox();
        chkMale = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Registration");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 330, 50));

        counsellingJLabel.setText("Would you require Mental Health Counselling?");
        add(counsellingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 220, 20));

        zipcodeJLabel.setText("ZipCode:");
        add(zipcodeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 80, -1));

        addressJLabel.setText("Street Address:");
        add(addressJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 80, 20));

        nameJLabel.setText("Full Name:");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, 20));

        cityJLabel.setText("City:");
        add(cityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 80, 30));

        stateJLabel.setText("State:");
        add(stateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 80, 20));

        phoneJLabel.setText("Phone Number:");
        add(phoneJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 264, 90, 20));

        emailJLabel.setText("Email:");
        add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 90, 20));

        sexJLabel.setText("Sex:");
        add(sexJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 90, 20));

        aidJLabel.setText("Would you require Federal Aid?");
        add(aidJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 160, 20));
        add(cityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 160, -1));

        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, -1));

        stateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJTextFieldActionPerformed(evt);
            }
        });
        add(stateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 160, -1));

        zipcodeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeJTextFieldActionPerformed(evt);
            }
        });
        add(zipcodeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 160, -1));
        add(phoneJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 160, -1));
        add(emailJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 160, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 160, -1));

        chkFemale.setText("Female");
        add(chkFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        chkOthers.setText("Others");
        add(chkOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        chkYes1.setText("Yes");
        add(chkYes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        chkNo1.setText("No");
        add(chkNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        chkYes2.setText("Yes");
        add(chkYes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        chkNo2.setText("No");
        add(chkNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        chkMale.setText("Male");
        add(chkMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        btnRegister.setText("Register");
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void stateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJTextFieldActionPerformed

    private void zipcodeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JLabel aidJLabel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chkFemale;
    private javax.swing.JCheckBox chkMale;
    private javax.swing.JCheckBox chkNo1;
    private javax.swing.JCheckBox chkNo2;
    private javax.swing.JCheckBox chkOthers;
    private javax.swing.JCheckBox chkYes1;
    private javax.swing.JCheckBox chkYes2;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JLabel counsellingJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JTextField phoneJTextField;
    private javax.swing.JLabel sexJLabel;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JLabel zipcodeJLabel;
    private javax.swing.JTextField zipcodeJTextField;
    // End of variables declaration//GEN-END:variables
}
