/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RationingFacilitatorWorkArea;

import Business.Distributor.Distributor;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.VolunteeringHead.VolunteeringHead;
import Business.WorkQueue.FinanceRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rtspi
 */
public class RationingFacilitatorRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RationingFacilitatorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private OrganizationDirectory orgDir;
    private Organization organization;
    private VolunteeringHead volunteer;
    
    public RationingFacilitatorRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount useraccount,OrganizationDirectory orgDir, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        this.orgDir = orgDir;
        this.organization = organization;
        populateComboBox();
        populateTable();
        volunteerJComboBox.setSelectedIndex(0);
    }
    
    public void populateComboBox(){
        volunteerJComboBox.removeAllItems();
        for(Organization org1 : orgDir.getOrgList()){
            
            for(VolunteeringHead da: org1.getVolunteeringHeadDirectory().getVolunteersList()){
                
                    volunteerJComboBox.addItem(da);
                
                
            }
            
        }
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        volunteerJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rationing Facilitator Work Area");

        btnAccept.setText("Accept Request");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject Request");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        jLabel2.setText("Assign Volunteer:");

        btnProcess.setText("Process Request");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request Number", "Request Name", "User Name", "User Contact", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequests);

        volunteerJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAccept)
                                .addGap(126, 126, 126)
                                .addComponent(btnReject))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(volunteerJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(btnProcess))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(559, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volunteerJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addComponent(btnProcess)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int row = tblRequests.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        FinanceRequest fReq=(FinanceRequest)tblRequests.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Request is already accepted", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Volunteering Head")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
        
//        FinanceRequest fReq=(FinanceRequest)tblRequests.getValueAt(row, 1);
        fReq.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "Request Accepted successfully!!!");
        } 
        populateTable();
        
        
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int row = tblRequests.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        FinanceRequest fReq=(FinanceRequest)tblRequests.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Volunteering Head")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        
        fReq.setStatus("Processed - Sent to Volunteering Head");
        volunteer.getFinanceRequestDirectory().addFinanceRequest(fReq);
        JOptionPane.showMessageDialog(null, "Request Processed Successfully!!!");
        } 
        populateTable();
        
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void volunteerJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerJComboBoxActionPerformed
        // TODO add your handling code here:
        volunteer = (VolunteeringHead)volunteerJComboBox.getSelectedItem();
    }//GEN-LAST:event_volunteerJComboBoxActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        
         int row = tblRequests.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        FinanceRequest fReq=(FinanceRequest)tblRequests.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Request is accepted already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Volunteering Head")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        
        fReq.setStatus("Rejected");
//        dist.getFinanceRequestDirectory().addFinanceRequest(fReq);
        JOptionPane.showMessageDialog(null, "Request Rejected!!!");
        } 
        populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    private javax.swing.JComboBox volunteerJComboBox;
    // End of variables declaration//GEN-END:variables
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
         model.setRowCount(0);
             Distributor dist =organization.getDistributorDirectory().findUserByUserName(useraccount.getUsername());
           for(FinanceRequest req : dist.getFinanceRequestDirectory().getFinanceRequestList()){
               System.out.println(req.getUser().getName());
            Object[] row = new Object[5];
            row[0] = req.getRequestNumber();
            row[1] = req;
            row[2] = req.getUser().getName();
            row[3] = req.getUser().getContactNumber();
            row[4] = req.getStatus();
            model.addRow(row);
        }   
        }
}
