/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GOVTRepresentative;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class GOVTRepresentativeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GOVTRepresentativeWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    public GOVTRepresentativeWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRequestHistory = new javax.swing.JButton();
        btnCreateUnits = new javax.swing.JButton();
        btnManageRequests = new javax.swing.JButton();
        rightGOVTRepresentativeJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Government Representative");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnRequestHistory.setBackground(new java.awt.Color(0, 255, 204));
        btnRequestHistory.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRequestHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestHistory.setText("Requests History");
        btnRequestHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHistoryActionPerformed(evt);
            }
        });

        btnCreateUnits.setBackground(new java.awt.Color(0, 255, 204));
        btnCreateUnits.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCreateUnits.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUnits.setText("Create Units");
        btnCreateUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUnitsActionPerformed(evt);
            }
        });

        btnManageRequests.setBackground(new java.awt.Color(0, 255, 204));
        btnManageRequests.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRequests.setText("Manage Requests");
        btnManageRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(btnRequestHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(71, Short.MAX_VALUE)
                    .addComponent(btnManageRequests)
                    .addGap(58, 58, 58)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(btnCreateUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRequestHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(509, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(736, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(btnManageRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(643, Short.MAX_VALUE)))
        );

        rightGOVTRepresentativeJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rightGOVTRepresentativeJPanelLayout = new javax.swing.GroupLayout(rightGOVTRepresentativeJPanel);
        rightGOVTRepresentativeJPanel.setLayout(rightGOVTRepresentativeJPanelLayout);
        rightGOVTRepresentativeJPanelLayout.setHorizontalGroup(
            rightGOVTRepresentativeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        rightGOVTRepresentativeJPanelLayout.setVerticalGroup(
            rightGOVTRepresentativeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightGOVTRepresentativeJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightGOVTRepresentativeJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHistoryActionPerformed
        // TODO add your handling code here:
        RequestHistoryRepresentativeJPanel manageRequestsHistoryJPanel = new RequestHistoryRepresentativeJPanel(rightGOVTRepresentativeJPanel, enterprise);
        rightGOVTRepresentativeJPanel.add("manageRequestsHistoryJPanel", manageRequestsHistoryJPanel);
        CardLayout layout = (CardLayout) rightGOVTRepresentativeJPanel.getLayout();
        layout.next(rightGOVTRepresentativeJPanel);
    }//GEN-LAST:event_btnRequestHistoryActionPerformed

    private void btnCreateUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUnitsActionPerformed
        // TODO add your handling code here:
        CreateUnitsRepresentativeJPanel createUnitRequestsJPanel = new CreateUnitsRepresentativeJPanel(rightGOVTRepresentativeJPanel, enterprise);
        rightGOVTRepresentativeJPanel.add("createUnitRequestsJPanel", createUnitRequestsJPanel);
        CardLayout layout = (CardLayout) rightGOVTRepresentativeJPanel.getLayout();
        layout.next(rightGOVTRepresentativeJPanel);
    }//GEN-LAST:event_btnCreateUnitsActionPerformed

    private void btnManageRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRequestsActionPerformed
        // TODO add your handling code here:
        ManageRequestsRepresentativeJPanel manageRequestsJPanel = new ManageRequestsRepresentativeJPanel(rightGOVTRepresentativeJPanel, enterprise);
        rightGOVTRepresentativeJPanel.add("manageRequestsJPanel", manageRequestsJPanel);
        CardLayout layout = (CardLayout) rightGOVTRepresentativeJPanel.getLayout();
        layout.next(rightGOVTRepresentativeJPanel);
    }//GEN-LAST:event_btnManageRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUnits;
    private javax.swing.JButton btnManageRequests;
    private javax.swing.JButton btnRequestHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel rightGOVTRepresentativeJPanel;
    // End of variables declaration//GEN-END:variables
}
