/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinanceAdminWorkArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class FinanceAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount useraccount;
    Organization org;
    Ecosystem system;

    /**
     * Creates new form FinanceAdminWorkAreaJPanel
     */
    public FinanceAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization org, Enterprise enterprise, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.system = system;
        this.org = org;
        manageOrganization();
    }

    private void manageOrganization(){
        lblManageOrganization.setBackground(new Color(236,113,107));
        lblManageEmployees.setBackground(new Color(215,81,81));
        lblManageUnits.setBackground(new Color(215,81,81));
        FinanceAdminManageOrganizationJPanel manageOrganizationJPanel = new FinanceAdminManageOrganizationJPanel(rightFinanceAdminJPanel, enterprise, enterprise.getOrganizationDirectory());
        rightFinanceAdminJPanel.add("FinanceAdminManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) rightFinanceAdminJPanel.getLayout();
        layout.next(rightFinanceAdminJPanel);
    }
        private void manageEmployee(){
        
        lblManageEmployees.setBackground(new Color(236,113,107));
        lblManageOrganization.setBackground(new Color(215,81,81));
        lblManageUnits.setBackground(new Color(215,81,81));
        FinanceAdminManageEmployeesJPanel manageEmployeeJPanel = new FinanceAdminManageEmployeesJPanel(rightFinanceAdminJPanel, enterprise, enterprise.getOrganizationDirectory());
        rightFinanceAdminJPanel.add("FinanceAdminManageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) rightFinanceAdminJPanel.getLayout();
        layout.next(rightFinanceAdminJPanel);
    }
    
    private void manageUnits(){
        
        lblManageUnits.setBackground(new Color(236,113,107));
        lblManageOrganization.setBackground(new Color(215,81,81));
        lblManageEmployees.setBackground(new Color(215,81,81));      
        FinanceAdminManageUnitJPanel muajp = new FinanceAdminManageUnitJPanel(rightFinanceAdminJPanel, enterprise);
        rightFinanceAdminJPanel.add("FinanceAdminManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) rightFinanceAdminJPanel.getLayout();
        layout.next(rightFinanceAdminJPanel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financeAdminJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblManageEmployees = new javax.swing.JLabel();
        lblManageUnits = new javax.swing.JLabel();
        lblManageOrganization = new javax.swing.JLabel();
        rightFinanceAdminJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        financeAdminJPanel.setBackground(new java.awt.Color(0, 204, 204));
        financeAdminJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        financeAdminJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FINANCE ADMIN SYSTEM");
        financeAdminJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 270, 30));

        lblManageEmployees.setBackground(new java.awt.Color(255, 255, 255));
        lblManageEmployees.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblManageEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageEmployees.setText("Manage Employees");
        lblManageEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageEmployeesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblManageEmployeesMousePressed(evt);
            }
        });
        financeAdminJPanel.add(lblManageEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 125, 267, 36));

        lblManageUnits.setBackground(new java.awt.Color(255, 255, 255));
        lblManageUnits.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblManageUnits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUnits.setText("Manage Units");
        lblManageUnits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageUnitsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblManageUnitsMousePressed(evt);
            }
        });
        financeAdminJPanel.add(lblManageUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 172, 267, 36));

        lblManageOrganization.setBackground(new java.awt.Color(255, 255, 255));
        lblManageOrganization.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblManageOrganization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageOrganization.setText("Manage Organizations");
        lblManageOrganization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageOrganizationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblManageOrganizationMousePressed(evt);
            }
        });
        financeAdminJPanel.add(lblManageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 78, 267, 36));

        rightFinanceAdminJPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightFinanceAdminJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(financeAdminJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightFinanceAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financeAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(rightFinanceAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblManageOrganizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageOrganizationMouseClicked
        // TODO add your handling code here:
        manageOrganization();
    }//GEN-LAST:event_lblManageOrganizationMouseClicked

    private void lblManageEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageEmployeesMouseClicked
        // TODO add your handling code here:
        manageEmployee();
    }//GEN-LAST:event_lblManageEmployeesMouseClicked

    private void lblManageUnitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUnitsMouseClicked
        // TODO add your handling code here:
        manageUnits();
    }//GEN-LAST:event_lblManageUnitsMouseClicked

    private void lblManageEmployeesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageEmployeesMousePressed
        // TODO add your handling code here:
        manageEmployee();
    }//GEN-LAST:event_lblManageEmployeesMousePressed

    private void lblManageOrganizationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageOrganizationMousePressed
        // TODO add your handling code here:
        manageOrganization();
    }//GEN-LAST:event_lblManageOrganizationMousePressed

    private void lblManageUnitsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUnitsMousePressed
        // TODO add your handling code here:
        manageUnits();
    }//GEN-LAST:event_lblManageUnitsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel financeAdminJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblManageEmployees;
    private javax.swing.JLabel lblManageOrganization;
    private javax.swing.JLabel lblManageUnits;
    private javax.swing.JPanel rightFinanceAdminJPanel;
    // End of variables declaration//GEN-END:variables
}
