/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BackgroundCheckAdminWorkArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author juhip
 */
public class BackgroundCheckAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BackgroundCheckJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    Ecosystem system;
    Organization organization;
    UserAccount userAcc;
    OrganizationDirectory orgDir;
    
    public BackgroundCheckAdminJPanel(JPanel userProcessContainer, Ecosystem system, Enterprise enterprise,UserAccount userAcc, Organization organization) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
        this.userAcc = userAcc;
        this.orgDir = orgDir;
    }
    
    
    private void manageBGRequests(){
        btnManageRequests.setBackground(new Color(236,113,107));
        btnRequestHistory.setBackground(new Color(215,81,81));
        ManageBGRequestsJPanel manageBGRequestsJPanel = new ManageBGRequestsJPanel(rightBackgroundCheckJPanel, enterprise, userAcc, enterprise.getOrganizationDirectory(), organization);
        rightBackgroundCheckJPanel.add("manageBGRequestsJPanel", manageBGRequestsJPanel);
        CardLayout layout = (CardLayout) rightBackgroundCheckJPanel.getLayout();
        layout.next(rightBackgroundCheckJPanel);        
    }
    
    
    private void bgHistory(){
        btnRequestHistory.setBackground(new Color(236,113,107));
        btnManageRequests.setBackground(new Color(215,81,81));
        BGHistoryJPanel bgHistoryJPanel = new BGHistoryJPanel(rightBackgroundCheckJPanel, enterprise,userAcc, enterprise.getOrganizationDirectory(), organization);
        rightBackgroundCheckJPanel.add("BGHistoryJPanel", bgHistoryJPanel);
        CardLayout layout = (CardLayout) rightBackgroundCheckJPanel.getLayout();
        layout.next(rightBackgroundCheckJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundCheckJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnManageRequests = new javax.swing.JButton();
        btnRequestHistory = new javax.swing.JButton();
        rightBackgroundCheckJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        backgroundCheckJPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundCheckJPanel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Background Check Admin");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnManageRequests.setBackground(new java.awt.Color(0, 255, 204));
        btnManageRequests.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRequests.setText("Manage Requests");
        btnManageRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRequestsActionPerformed(evt);
            }
        });

        btnRequestHistory.setBackground(new java.awt.Color(0, 255, 204));
        btnRequestHistory.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRequestHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestHistory.setText("Request History");
        btnRequestHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundCheckJPanelLayout = new javax.swing.GroupLayout(backgroundCheckJPanel);
        backgroundCheckJPanel.setLayout(backgroundCheckJPanelLayout);
        backgroundCheckJPanelLayout.setHorizontalGroup(
            backgroundCheckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundCheckJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundCheckJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundCheckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRequestHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRequests))
                .addGap(59, 59, 59))
        );
        backgroundCheckJPanelLayout.setVerticalGroup(
            backgroundCheckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundCheckJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnManageRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRequestHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );

        rightBackgroundCheckJPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightBackgroundCheckJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundCheckJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightBackgroundCheckJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundCheckJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightBackgroundCheckJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRequestsActionPerformed
        // TODO add your handling code here:
        manageBGRequests();
    }//GEN-LAST:event_btnManageRequestsActionPerformed

    private void btnRequestHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHistoryActionPerformed
        // TODO add your handling code here:
        bgHistory();
    }//GEN-LAST:event_btnRequestHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundCheckJPanel;
    private javax.swing.JButton btnManageRequests;
    private javax.swing.JButton btnRequestHistory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel rightBackgroundCheckJPanel;
    // End of variables declaration//GEN-END:variables
}
