/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BackgroundCheckAdminWorkArea;

import Business.Enterprise.Enterprise;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class ManageBGRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageBGRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    public ManageBGRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnCompleted = new javax.swing.JButton();
        facilitatorJComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 63, 642, 94));

        btnAccept.setText("Accept Request");
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 200, -1, -1));

        btnReject.setText("Reject Request");
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 200, -1, -1));

        btnCompleted.setText("Complete Request");
        add(btnCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 200, -1, -1));

        facilitatorJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(facilitatorJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 293, 176, 29));

        jLabel1.setText("Assign Facilitator:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 293, 100, 29));

        btnProcess.setText("Process Request");
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 429, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCompleted;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnReject;
    private javax.swing.JComboBox<String> facilitatorJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables
}
